<template>
    <v-btn @mouseenter="rotate = true" @mouseleave="rotate = false" v-bind="$attrs" @click="model = true">
        <v-icon :class="{ 'rotate-center': rotate }" v-if="props.icon != null">mdi-{{ props.icon }}</v-icon>
        {{ props.label }}
    </v-btn>
    <v-dialog v-model="model" max-width="500">
        <v-card>
            <v-card-text>
                <slot name="message"></slot>
            </v-card-text>
            <v-card-actions>
                <v-spacer />
                <v-btn color="primary" @click="() => { model = false; emits('confirm') }">{{t('confirm')}}</v-btn>
                <v-btn color="secondary" @click="model = false">{{t('cancel')}}</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>
<script setup>
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
const { t } = useI18n();
let model = ref(false);
let rotate = ref(false);
const emits = defineEmits(['confirm']);
const props = defineProps({
    icon: {
        type: String,
        default: null
    },
    label: {
        type: String,
        default: null
    }
})
</script>
<style>
.rotate-center {
    animation: rotate-center 0.6s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-29 21:55:9
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
@keyframes rotate-center {
    0% {
        transform: rotate(0);
    }

    100% {
        transform: rotate(360deg);
    }
}
</style>