<template>
    <v-text-field @input="hor  =  true" label="write your name" v-model="name">
        <template v-slot:prepend>
            <v-icon :class="{  'wobble-hor-bottom':  hor  }">mdi-feather</v-icon>
        </template>
    </v-text-field>
</template>
<script setup>
import { ref } from 'vue';
let name = ref('');
let hor = ref(false);
</script>
<style>
.wobble-hor-bottom {
    animation: wobble-hor-bottom 0.8s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-29 22:52:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-bottom
 * ----------------------------------------
 */
@keyframes wobble-hor-bottom {

    0%,
    100% {
        transform: translateX(0%);
        transform-origin: 50% 50%;
    }

    15% {
        transform: translateX(-30px) rotate(-6deg);
    }

    30% {
        transform: translateX(15px) rotate(6deg);
    }

    45% {
        transform: translateX(-15px) rotate(-3.6deg);
    }

    60% {
        transform: translateX(9px) rotate(2.4deg);
    }

    75% {
        transform: translateX(-6px) rotate(-1.2deg);
    }
}
</style>